"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var pedidos_1 = require("./pedidos");
var itemPedidos_1 = require("./itemPedidos");
var cliente_1 = require("./cliente");
var cliente = new cliente_1.Cliente('Nome', '999.999.999-99', 'Email', 'Endereço');
var item1 = new itemPedidos_1.ItemPedido(1, 'Item 1', 10, 100);
var item2 = new itemPedidos_1.ItemPedido(2, 'Item 2', 20, 100);
var item3 = new itemPedidos_1.ItemPedido(3, 'Item 3', 30, 100);
var pedido = new pedidos_1.Pedidos(cliente);
console.log(pedido.calcularValorTotal());
pedido.adicionarItem(item1);
pedido.adicionarItem(item2);
pedido.adicionarItem(item3);
console.log(pedido.calcularValorTotal());
pedido.removerItem(1);
console.log(pedido.calcularValorTotal());
console.log(pedido.status);
console.log(pedido.cliente);
console.log(pedido.itemsPedidos);
console.log(pedido.data);
console.log(pedido.numero);
console.log(pedido);
console.log(pedido.cliente.nome);
