"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var personagem_1 = require("./personagem");
var personagem1 = new personagem_1.Personagem();
personagem1.nome = "Gandalf";
personagem1.numeroVidas = 5;
personagem1.nivel = "Avançado";
personagem1.atacar();
personagem1.receberDano(3);
personagem1.recuperarPontosVida(2);
